apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: replicaset-app
    env: prod-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod-pod
  template:
    metadata:
      name: my-pod
      labels:
        app: ngnix-app
        env: prod-pod
    spec:
      containers:
        - name: ngnix-from-rs
          image: nginx